name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Dependencies
      run: sudo apt -y install libgtk-3-dev
      # TODO: use the make.sh for releases as they're optimized.
    - name: make gtk
      run: TARGET=gtk make

  macos:
   runs-on: macos-13
   steps:
   - uses: actions/checkout@v4
   - name: Dependencies
     run: brew install gtk+3 libomp llvm
   - name: make gtk
     # Using brew's llvm, because apple's does not support -fopenmp
     run: CC=/usr/local/opt/llvm/bin/clang CXX=/usr/local/opt/llvm/bin/clang++ TARGET=gtk make

  windows:
    runs-on: windows-latest
    steps: 
    - uses: actions/checkout@v4
    - name: make
      run: CC=cl CXX=cl make
